
CREATE_VISITORS_TABLE = """
CREATE TABLE IF NOT EXISTS visitors (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_HEALTH_TABLE = """
CREATE TABLE IF NOT EXISTS health_report (
    id SERIAL PRIMARY KEY,
    status TEXT NOT NULL,
    info TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""
