services:
  # -------------------------
  # WEB SERVICE (dashboard)
  # -------------------------
  - name: project-cicd-lumen-web-worker
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LUMEN_WORKER_STATUS_URL
        fromService:
          name: lumen-worker
          type: worker
          property: url
      - key: PYTHON_VERSION
        value: 3.11.6

  # -------------------------
  # WORKER SERVICE
  # -------------------------
  - name: lumen-worker
    type: worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: LUMEN_WEB_HEALTH_URL
        fromService:
          name: project-cicd-lumen-web-worker
          type: web
          property: url
      - key: PYTHON_VERSION
        value: 3.11.6
